#!/usr/bin/env python3
"""Build and verify paragraph-aligned bilingual study documents."""
import argparse
import hashlib
import json
import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WORK = ROOT / 'translations/zh-CN'
OUT = ROOT / 'docs/bilingual'


def sources():
    return sorted(p for p in ROOT.rglob('*.md') if not any(x in p.relative_to(ROOT).parts for x in ('.git', '.translation-work', 'translations', 'bilingual')))


def chunks(text):
    result, current, fence = [], [], None
    lines = text.splitlines(keepends=True)
    front = bool(lines and lines[0].strip() == '---')
    for i, line in enumerate(lines):
        current.append(line)
        stripped = line.strip()
        if front:
            if i > 0 and stripped == '---':
                front = False
            continue
        match = re.match(r'^\s*(`{3,}|~{3,})', line)
        if match:
            token = match.group(1)
            if fence is None:
                fence = token
            elif token[0] == fence[0] and len(token) >= len(fence):
                fence = None
        if not stripped and fence is None:
            if ''.join(current).strip():
                result.append(''.join(current))
                current = []
    if current:
        if ''.join(current).strip():
            result.append(''.join(current))
        elif result:
            result[-1] += ''.join(current)
    assert ''.join(result) == text
    return result


def init():
    WORK.mkdir(exist_ok=True)
    for p in sources():
        rel = p.relative_to(ROOT).as_posix()
        text = p.read_text()
        data = {'source': rel, 'sha256': hashlib.sha256(text.encode()).hexdigest(), 'blocks': [{'en': c, 'zh': None} for c in chunks(text)]}
        dest = WORK / (rel + '.json')
        dest.parent.mkdir(parents=True, exist_ok=True)
        if not dest.exists():
            dest.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n')
    print(f'Initialized missing translation records for {len(sources())} source documents.')


def local_links(text, source, target):
    # Link rewriting is limited to Markdown destinations; original wording stays intact.
    def replace(m):
        dest = m.group(2)
        if re.match(r'^[a-zA-Z][a-zA-Z0-9+.-]*:', dest) or dest.startswith(('#', '/')):
            return m.group(0)
        path, sep, anchor = dest.partition('#')
        actual = source.parent / path
        if actual.suffix == '.md' or (actual.is_dir() and any(actual.rglob('*.md'))):
            return m.group(0)
        rewritten = os.path.relpath(actual, target.parent)
        return m.group(1) + rewritten + (sep + anchor if sep else '') + m.group(3)
    return re.sub(r'(!?\[[^\]\n]*\]\()([^\s)]+)(\))', replace, text)


def render(source, data):
    dest = OUT / source.relative_to(ROOT)
    backlink = os.path.relpath(source, dest.parent)
    result = [f'<!-- Generated by scripts/bilingual.py. Source SHA256: {data["sha256"]} -->\n', f'[英文源文件 / English source]({backlink})\n\n']
    for i, block in enumerate(data['blocks']):
        en = block['en'].rstrip()
        zh = block['zh'].rstrip()
        if zh.strip() == en.strip() and re.match(r'^#{1,6} ', zh):
            zh += '（中文）'
        if i == 0 and en.startswith('---\n'):
            en = '```yaml\n' + en + '\n```'
            zh = '```yaml\n' + zh + '\n```'
        # Keep one collapsible container, with its English and Chinese labels.
        zh = re.sub(r'</?details>', '', zh)
        zh = re.sub(r'<summary>(.*?)</summary>', r'**\1**', zh)
        result.append(f'<!-- en:{i} -->\n' + local_links(en, source, dest) + '\n\n')
        if zh.strip():
            result.append(f'<!-- zh:{i} -->\n> **中文**\n>\n' + '\n'.join('> ' + line if line else '>' for line in local_links(zh, source, dest).splitlines()) + '\n\n')
    return ''.join(result).rstrip() + '\n'


def check_local_links(source, data, rendered):
    """Reject missing targets introduced by moving a document into the study tree."""
    links = re.compile(r'!?\[[^\]\n]*\]\(([^\s)]+)\)')
    source_missing = set()
    for block in data['blocks']:
        for link in links.findall(block['en']):
            path = link.partition('#')[0]
            if path and not re.match(r'^[a-zA-Z][a-zA-Z0-9+.-]*:', path) and not path.startswith('/'):
                if not (source.parent / path).exists():
                    source_missing.add(path)
    errors = []
    dest = OUT / source.relative_to(ROOT)
    for link in links.findall(rendered):
        path = link.partition('#')[0]
        if not path or re.match(r'^[a-zA-Z][a-zA-Z0-9+.-]*:', path) or path.startswith('/'):
            continue
        if not (dest.parent / path).exists():
            if not any((dest.parent / path).resolve() == (source.parent / missing).resolve() for missing in source_missing):
                errors.append(f'{source.relative_to(ROOT)}: introduced missing local link {link}')
    return errors


def build(check=False):
    errors = []
    for source in sources():
        rel = source.relative_to(ROOT).as_posix()
        data_path = WORK / (rel + '.json')
        if not data_path.exists():
            errors.append(f'{rel}: translation missing')
            continue
        data = json.loads(data_path.read_text())
        original = source.read_text()
        if data['sha256'] != hashlib.sha256(original.encode()).hexdigest():
            errors.append(f'{rel}: source hash changed; review translations before rebuilding')
        if ''.join(b['en'] for b in data['blocks']) != original:
            errors.append(f'{rel}: English differs from source')
        missing = [i for i, b in enumerate(data['blocks']) if not isinstance(b['zh'], str) or not b['zh'].strip()]
        if missing:
            errors.append(f'{rel}: {len(missing)} untranslated blocks')
            continue
        for i, block in enumerate(data['blocks']):
            en, zh = block['en'].strip(), block['zh'].strip()
            if re.findall(r'\]\(([^)]+)\)', en) != re.findall(r'\]\(([^)]+)\)', zh):
                # Ordering can change naturally, but destinations must be preserved.
                if sorted(re.findall(r'\]\(([^)]+)\)', en)) != sorted(re.findall(r'\]\(([^)]+)\)', zh)):
                    errors.append(f'{rel}:{i}: link destinations differ')
            if re.match(r'^#{1,6} ', en) and not re.match(r'^#{1,6} ', zh):
                errors.append(f'{rel}:{i}: heading missing')
            prose = re.sub(r'```.*?```|~~~.*?~~~', '', en, flags=re.S)
            if re.search(r'[A-Za-z]{4} [A-Za-z]{4}', prose) and not re.search(r'[\u3400-\u9fff]', zh) and not en.startswith(('#', '<')):
                errors.append(f'{rel}:{i}: prose has no Chinese translation')
        dest = OUT / rel
        result = render(source, data)
        if check:
            errors.extend(check_local_links(source, data, result))
        if check:
            if not dest.exists() or dest.read_text() != result:
                errors.append(f'{rel}: rendered document missing or out of date')
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(result)
    if errors:
        raise SystemExit('\n'.join(errors))
    print(f'{"Verified" if check else "Built"} {len(sources())} bilingual documents.')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('command', choices=['init', 'build', 'check'])
    args = parser.parse_args()
    init() if args.command == 'init' else build(check=args.command == 'check')
